icons:
    - sceneId: AnubsA69
      icon: OStim/sexual/sixtynine_mf
    - sceneId: AnubsAanaldoggy
      icon: OStim/sexual/doggystyle_mf
    - sceneId: AnubsAdultDoggy2
      icon: OStim/sexual/doggystyle_mf
    - sceneId: AnubsAdultFootjob
      icon: OStim/sexual/footjob_mf
    - sceneId: AnubsAdultLs
      icon: OStim/sexual/sideways_mf
    - sceneId: AnubsAdultMatingpress
      icon: OStim/sexual/matingpress_mf
    - sceneId: AnubsAdultmissionary
      icon: OStim/sexual/missionary_mf
    - sceneId: AnubsAdultRcg2
      icon: OStim/sexual/reversecowgirl_alt_mf
    - sceneId: AnubsAdultSleep
      icon: OStim/sexual/missionary_mf
    - sceneId: AnubsAdultSpooning
      icon: OStim/sexual/sideways_behind_mf
    - sceneId: AnubsAdultTease2
      icon: OStim/sexual/grindingpenis_mf
    - sceneId: AnubsAm2
      icon: OStim/sexual/missionary_mf
    - sceneId: AnubsAnubdoggystyle
      icon: OStim/sexual/doggystyle_mf
    - sceneId: AnubsAPronebone
      icon: ""
    - sceneId: AnubsAShotacowgirl
      icon: OStim/sexual/cowgirl_mf
    - sceneId: AnubsAsq
      icon: OStim/sexual/thighjob_mf
    - sceneId: AnubsASt
      icon: OStim/sexual/thighjob_mf
    - sceneId: AnubsBm
      icon: OStim/sexual/missionary_mf
    - sceneId: AnubsD6b
      icon: OStim/sexual/missionary_mf
    - sceneId: AnubsD6s
      icon: OStim/sexual/blowjob_mf
    - sceneId: AnubsDeltafeet
      icon: OStim/sexual/cowgirl_feetface_mf
    - sceneId: AnubsForeplay
      icon: OStim/sexual/cunnilingus_mf
    - sceneId: AnubsHold
      icon: OStim/sexual/carryingsex_mf
    - sceneId: AnubsImpreg
      icon: OStim/sexual/missionary_mf
    - sceneId: AnubsJacko
      icon: OStim/sexual/doggystyle_mf
    - sceneId: AnubsLegupfuck
      icon: OStim/sexual/missionary_mf
    - sceneId: AnubsLustcowgirl
      icon: OStim/sexual/cowgirl_holdinghips_mf
    - sceneId: AnubsMf
      icon: ""
    - sceneId: AnubsMisionary
      icon: OStim/sexual/missionary_mf
    - sceneId: AnubsMmocg
      icon: OStim/sexual/reversecowgirl_mf
    - sceneId: AnubsNelson
      icon: ""
    - sceneId: AnubsRcowgirl
      icon: OStim/sexual/reversecowgirl_mf
    - sceneId: AnubsRune
      icon: ""
    - sceneId: AnubsSinner
      icon: OStim/sexual/thighjob_mf
    - sceneId: AnubsSquatingbj
      icon: OStim/sexual/blowjob_mf
    - sceneId: AnubsStandingnew
      icon: ""
    - sceneId: AnubsTraining
      icon: OStim/sexual/carryingsex_mf
    - sceneId: AnubsVamp1
      icon: OStim/sensual/vampirebite
    - sceneId: AnubsVampfemale
      icon: OStim/sensual/vampirebite
    - sceneId: AnubsAhb
      icon: ""
    - sceneId: AnubsFfmm
      icon: ""
    - sceneId: AnubsFfmMistress
      icon: ""
    - sceneId: AnubsFfmSleep
      icon: OStim/positional/lyingdown_mff
    - sceneId: AnubsFmm3some
      icon: ""
    - sceneId: AnubsGangbang
      icon: ""
    - sceneId: AnubsMagickFfm
      icon: OStim/sexual/blowjob_mff
