module:
    name: AnubsHuman
    inputPath: D:\animations\anubs\1537070476_AnubSLAL022023SSELLver\00 Data\SLAL
        H\Meshes\actors\character\animations\Anubs Human
    slalJsonConfig: D:\animations\anubs\1537070476_AnubSLAL022023SSELLver\00
        Data\SLAL H\SLAnims\json\HUMAN NEW.json
    include: []
    exclude:
        - AnubsAnubagra
        - AnubsBound
        - AnubsChained
        - AnubsChainedCelling
        - AnubsChaingallow
        - AnubsFf
        - AnubsHumandoggy
        - AnubsMagick
        - AnubsMindControl
        - AnubsMissionaryR
        - AnubsParalysis
        - AnubsPole
        - AnubsRape
        - AnubsRejection
        - AnubsSDefeat
        - AnubsUnc
        - AnubsUnc2
        - AnubsVs
        - AnubsX
        - AnubsBoundtable
        - AnubsBoundtable2
        - AnubsFcowgirl
        - AnubsHogtie3some
        - AnubsChoke
        - AnubsThronechain
        - AnubsChest
        - AnubsFfmfemdom2
        - AnubsFfmfemdom
        - AnubsFfmFemdom3
        - AnubsAAmazon
        - AnubsAnubdomcow
        - AnubsAnubfemdom
        - AnubsFacesit
        - AnubsFemfoot
        - AnubsFfmReversal
        - AnubsHge
        - AnubsAfc2
        - AnubsAmazon
        - AnubsKnife
        - AnubsMbf
        - AnubsSwordCg
        - AnubsHypno
        - AnubsLesbiandomination
        - AnubsLesbian
        - AnubsLesbianFf
        - AnubsFffmistress
        - AnubsBarrelMast
        - AnubsDildo
        - AnubsFMast1
        - AnubsFMast2
        - AnubsABedsleep
        - AnubsAChairCg
        - AnubsAdultBarTable
        - AnubsAdultBath
        - AnubsAdultStool
        - AnubsASide
        - AnubsASofa
        - AnubsBedP
        - AnubsCaged
        - AnubsDrunk
        - AnubsAdultRbed2
        - AnubsFfmBed
        - AnubsTw
        - AnubsChairDoggy
        - AnubsThroneFemdom
        - AnubsAdultBench
        - AnubsChairfemdom
        - AnubsCancun
        - AnubsChaurusTest
        - AnubsMmfRape
    nemesisPrefix: anuhum
