icons:
    - sceneId: BillyyFmaststaff
      icon: OStim/sexual/strapon_insert_vert
    - sceneId: BillyyFmast4
      icon: OStim/sexual/femalemasturbation
    - sceneId: BillyyFmast3
      icon: OStim/sexual/femalemasturbation
    - sceneId: BillyyFmast2
      icon: OStim/sexual/femalemasturbation
    - sceneId: BillyyFmast1
      icon: OStim/sexual/femalemasturbation
