icons:
    - sceneId: LeitoAfFSoloChair
      icon: OStim/sexual/femalemasturbation
    - sceneId: LeitoAfUnicorn
      icon: OStim/sexual/missionary_mf
    - sceneId: LeitoAfThroneMissionary
      icon: OStim/sexual/missionary_mf
    - sceneId: LeitoAfThroneDoggy
      icon: OStim/sexual/doggystyle_mf
    - sceneId: LeitoAfThroneCunnilingus
      icon: OStim/sexual/cunnilingus_mf
    - sceneId: LeitoAfThroneCowgirl
      icon: OStim/sexual/chair/cowgirl_mf
    - sceneId: LeitoAfThroneBj
      icon: OStim/sexual/blowjob_mf
    - sceneId: LeitoAfThroneAnalReCow
      icon: OStim/sexual/chair/reversecowgirl_mf
    - sceneId: LeitoAfThroneAnalDoggy
      icon: OStim/sexual/doggystyle_mf
    - sceneId: LeitoAfBedMissionary
      icon: OStim/sexual/missionary_mf
    - sceneId: LeitoAfBedFeetMissionary
      icon: OStim/sexual/missionary_mf
    - sceneId: LeitoAfBedDoggy
      icon: OStim/sexual/doggystyle_mf
    - sceneId: LeitoAfBedCowgirl
      icon: OStim/sexual/cowgirl_mf
    - sceneId: LeitoAfBedAnalReCow
      icon: OStim/sexual/reversecowgirl_mf
    - sceneId: LeitoAfBedAnalDoggy
      icon: OStim/sexual/doggystyle_mf
    - sceneId: LeitoAfBed69
      icon: OStim/sexual/sixtynine_mf
