icons:
    - sceneId: AnubsAdultBath
      icon: OStim/sexual/blowjob_lying_mf
    - sceneId: AnubsAdultStool
      icon: OStim/sexual/chair/reversecowgirl_mf
    - sceneId: AnubsASide
      icon: OStim/sexual/sideways_mf
    - sceneId: AnubsDrunk
      icon: OStim/sexual/table/missionary_mf
    - sceneId: AnubsAChairCg
      icon: OStim/sexual/chair/cowgirl_mf
    - sceneId: AnubsChairDoggy
      icon: OStim/sexual/doggystyle_mf
    - sceneId: AnubsChairfemdom
      icon: OStim/sexual/chair/reversecowgirl_mf
    - sceneId: AnubsThroneFemdom
      icon: OStim/sexual/chair/cowgirl_mf
    - sceneId: AnubsABedsleep
      icon: OStim/sexual/missionary_mf
    - sceneId: AnubsBedP
      icon: OStim/sexual/doggystyle_mm
    - sceneId: AnubsAdultBench
      icon: OStim/sexual/reversecowgirl_mf
    - sceneId: AnubsASofa
      icon: OStim/sexual/reversecowgirl_mf
    - sceneId: AnubsAdultBarTable
      icon: OStim/sexual/table/blowjob_lyingback_mf
    - sceneId: AnubsCaged
      icon: ""
    - sceneId: AnubsAdultRbed2
      icon: ""
    - sceneId: AnubsFfmBed
      icon: ""
    - sceneId: AnubsFfmFemdom3
      icon: ""
    - sceneId: AnubsTw
      icon: ""
