furnitureMap:
    bed:
        - AnubsAfAdultRbed2
        - AnubsAfABedsleep
        - AnubsAfBedP
        - AnubsAfFfmBed
    bench:
        - AnubsAfAdultBench
        - AnubsAfASofa
    chair:
        - AnubsAfAChairCg
        - AnubsAfChairfemdom
        - AnubsAfChairDoggy
        - AnubsAfThroneFemdom
        - AnubsAfTw
        - AnubsAfFfmFemdom3
    cookingpot: []
    shelf: []
    table:
        - AnubsAfAdultBarTable
    wall: []
