icons:
    - sceneId: AnubsAfAdultBath
      icon: OStim/sexual/blowjob_lying_mf
    - sceneId: AnubsAfAdultStool
      icon: OStim/sexual/chair/reversecowgirl_mf
    - sceneId: AnubsAfASide
      icon: OStim/sexual/sideways_mf
    - sceneId: AnubsAfDrunk
      icon: OStim/sexual/table/missionary_mf
    - sceneId: AnubsAfAChairCg
      icon: OStim/sexual/chair/cowgirl_mf
    - sceneId: AnubsAfChairDoggy
      icon: OStim/sexual/doggystyle_mf
    - sceneId: AnubsAfChairfemdom
      icon: OStim/sexual/chair/reversecowgirl_mf
    - sceneId: AnubsAfThroneFemdom
      icon: OStim/sexual/chair/cowgirl_mf
    - sceneId: AnubsAfABedsleep
      icon: OStim/sexual/missionary_mf
    - sceneId: AnubsAfBedP
      icon: OStim/sexual/doggystyle_mm
    - sceneId: AnubsAfAdultBench
      icon: OStim/sexual/reversecowgirl_mf
    - sceneId: AnubsAfASofa
      icon: OStim/sexual/reversecowgirl_mf
    - sceneId: AnubsAfAdultBarTable
      icon: OStim/sexual/table/blowjob_lyingback_mf
    - sceneId: AnubsAfCaged
      icon: ""
    - sceneId: AnubsAfAdultRbed2
      icon: ""
    - sceneId: AnubsAfFfmBed
      icon: ""
    - sceneId: AnubsAfFfmFemdom3
      icon: ""
    - sceneId: AnubsAfTw
      icon: ""
