icons:
    - sceneId: LeitoLesbianDildo2
      icon: ""
    - sceneId: LeitoLesbianDildo1
      icon: ""
    - sceneId: LeitoLesbian2
      icon: OStim/sexual/ff_69
    - sceneId: LeitoLesbian1
      icon: OStim/sexual/tribbing_ff
