furnitureMap:
    - animation: NibblesAfTablefuck
      furniture: bed
    - animation: NibblesAfSpankingchair
      furniture: chair
    - animation: NibblesAfSpanking
      furniture: chair
    - animation: NibblesAfChairdildo
      furniture: chair
    - animation: NibblesAfTablestandingbehind
      furniture: table
    - animation: NibblesAfTablestandingfront
      furniture: table
    - animation: NibblesAfWorkbench
      furniture: table
    - animation: NibblesAfLesbianhaycun
      furniture: table
