icons:
    - sceneId: NibblesAfWorkbench
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: NibblesAfTablestandingfront
      icon: OStim/sexual/table/missionary_mf
    - sceneId: NibblesAfTablestandingbehind
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: NibblesAfTablefuck
      icon: OStim/sexual/table/missionary_mf
    - sceneId: NibblesAfSpanking
      icon: OStim/sexual/spank_left_mf
    - sceneId: NibblesAfSpankingchair
      icon: OStim/sexual/spank_left_mf
    - sceneId: NibblesAfTentacledoggy
      icon: ""
    - sceneId: NibblesAfMimic
      icon: ""
    - sceneId: NibblesAfLesbianhaycun
      icon: OStim/sexual/cunnilingus_ff
    - sceneId: NibblesAfChairdildo
      icon: OStim/sexual/strapon_insert_vert
    - sceneId: NibblesAfDrunkmasturbation
      icon: OStim/sexual/femalemasturbation
