icons:
    - sceneId: LeitoFSoloToyReCowAnal
      icon: OStim/sexual/strapon_insert_vert
    - sceneId: LeitoFSoloToyCowgirlVag
      icon: OStim/sexual/strapon_insert_vert
    - sceneId: LeitoFSoloDildoVag
      icon: OStim/sexual/strapon_insert_vert
    - sceneId: LeitoFSoloDildoAnal
      icon: OStim/sexual/strapon_insert_vert
