module:
    name: LeitoSolo
    inputPath: D:\animations\leito\SLAL_AnimationsByLeito_v1.6\01-NonCreature\meshes\actors\character\animations\AnimationsByLeito
    slalJsonConfig: D:\animations\leito\SLAL_AnimationsByLeito_v1.6\01-NonCreature\SLAnims\json\AnimationsByLeito.json
    include:
        - LeitoFSoloDildoAnal
        - LeitoFSoloDildoVag
        - LeitoFSoloToyCowgirlVag
        - LeitoFSoloToyReCowAnal
    exclude: []
    nemesisPrefix: leisol
