module:
    name: AnubsSolo
    inputPath: D:\animations\anubs\1537070476_AnubSLAL022023SSELLver\00 Data\SLAL
        H\Meshes\actors\character\animations\Anubs Human
    slalJsonConfig: D:\animations\anubs\1537070476_AnubSLAL022023SSELLver\00
        Data\SLAL H\SLAnims\json\HUMAN NEW.json
    include:
        - AnubsBarrelMast
        - AnubsDildo
        - AnubsFMast1
        - AnubsFMast2
    exclude: []
    nemesisPrefix: anusol
