customScale:
    abg:
        - 1.15
        - null
    bggentle:
        - 1.15
        - null
    bgnelson:
        - 1.15
        - null
    bgwall:
        - 1.15
        - null
    bigguydoggy:
        - 1.15
        - null
    bigguysitting:
        - 1.15
        - null
    mmfbigguys:
        - 1.15
        - 1.15
        - null
