icons:
    - sceneId: NibblesStandingfuck4
      icon: OStim/sexual/thighjob_mf
    - sceneId: NibblesSidewaysfuck
      icon: OStim/sexual/sideways_mf
    - sceneId: NibblesScrew
      icon: OStim/sexual/sideways_mf
    - sceneId: NibblesReversecowgirl2
      icon: OStim/sexual/reversecowgirl_mf
    - sceneId: NibblesMissionary4
      icon: OStim/sexual/missionary_mf
    - sceneId: NibblesMissionary3
      icon: OStim/sexual/missionary_mf
    - sceneId: NibblesMissionary2
      icon: OStim/sexual/missionary_mf
    - sceneId: NibblesLapfuck
      icon: OStim/sexual/carryingsex_mf
    - sceneId: NibblesLapfuck2
      icon: OStim/sexual/carryingsex_mf
    - sceneId: NibblesFacesitting
      icon: OStim/sexual/facesitting_mf
    - sceneId: NibblesDoggystyle4
      icon: OStim/sexual/doggystyle_mf
    - sceneId: NibblesDoggystyle3
      icon: OStim/sexual/doggystyle_mf
    - sceneId: NibblesCowgirlfemdom
      icon: OStim/sexual/cowgirl_mf
    - sceneId: NibblesCowgirl6
      icon: OStim/sexual/cowgirl_mf
    - sceneId: NibblesCowgirl5
      icon: OStim/sexual/cowgirl_mf
    - sceneId: NibblesCowgirl4
      icon: OStim/sexual/cowgirl_holdinghips_mf
    - sceneId: NibblesCowgirl3
      icon: OStim/sexual/cowgirl_mf
    - sceneId: NibblesBlowjob2
      icon: OStim/sexual/blowjob_mf
    - sceneId: NibblesBellyflop
      icon: OStim/sexual/prone_mf
    - sceneId: NibblesBellyflop2
      icon: OStim/sexual/prone_mf
    - sceneId: NibblesAnalfingering
      icon: OStim/sexual/vaginalfingering_mf
    - sceneId: Nibbles69consensual
      icon: OStim/sexual/sixtynine_mf
