furnitureMap:
    - animation: BillyyAfChairdildo
      furniture: chair
    - animation: BillyyAfAlchemyworkbenchfuck
      furniture: table
    - animation: BillyyAfEnchantingworkbenchfuck
      furniture: table
