icons:
    - sceneId: BillyyAf3pgloryholespitroast
      icon: ""
    - sceneId: BillyyAfFurotub2
      icon: ""
    - sceneId: BillyyAfFurotub1
      icon: ""
    - sceneId: BillyyAfChairdildo
      icon: OStim/sexual/strapon_insert_vert
    - sceneId: BillyyAfEnchantingworkbenchfuck
      icon: ""
    - sceneId: BillyyAfAlchemyworkbenchfuck
      icon: OStim/sexual/missionary_mf
    - sceneId: BillyyAfGloryholestuckfuck
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: BillyyAfGloryholefuck
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: BillyyAfGloryholeblowjob
      icon: OStim/sexual/blowjob_mf
