objects:
    replaceObjects:
        BillyyAfChairdildo: {}
        BillyyAfFurotub1: {}
        BillyyAfFurotub2: {}
        BillyyAfAlchemyworkbenchfuck: {}
        BillyyAfEnchantingworkbenchfuck: {}
        BillyyAfGloryholefuck: {}
        BillyyAfGloryholestuckfuck: {}
        BillyyAfGloryholeblowjob: {}
        BillyyAf3pgloryholespitroast: {}
    skipObjects:
        BillyyAfAlchemyworkbenchfuck:
            - AOAWB
        BillyyAfEnchantingworkbenchfuck:
            - AOEncWB
        BillyyAfChairdildo:
            - AOChairA
