furnitureMap:
    - animation: Nck30AfMassagemadness
      furniture: bed
    - animation: Nck30AfSleazyrider
      furniture: bench
    - animation: Nck30AfTable1
      furniture: bench
    - animation: Nck30AfWildweekend
      furniture: bench
    - animation: Nck30AfBeachball
      furniture: chair
    - animation: Nck30AfChair1
      furniture: chair
    - animation: Nck30AfMountmilf
      furniture: chair
    - animation: Nck30AfTable2
      furniture: table
    - animation: Nck30AfGreekgoddess
      furniture: wall
