module:
    name: NCK30
    inputPath: D:\animations\NCK30 SLAL 3.9 SE\Meshes\actors\character\animations\NCK30
    slalJsonConfig: D:\animations\NCK30 SLAL 3.9 SE\SLAnims\json\NCK30.json
    include: []
    exclude: 
        - Nck30Assmasterpiece
        - Nck30Beachball
        - Nck30Chair1
        - Nck30Greekgoddess
        - Nck30Hottub
        - Nck30Massagemadness
        - Nck30Mountmilf
        - Nck30Shelf1
        - Nck30Sleazyrider
        - Nck30Table1
        - Nck30Table2
        - Nck30Wildweekend
        - Nck30Bedtimebreeding
        - Nck30Sundaysoulmate
        - Nck30Wallseduction
    nemesisPrefix: nck
