icons:
    - sceneId: Billyy3pgloryholespitroast
      icon: ""
    - sceneId: BillyyFurotub2
      icon: ""
    - sceneId: BillyyFurotub1
      icon: ""
    - sceneId: BillyyChairdildo
      icon: OStim/sexual/strapon_insert_vert
    - sceneId: BillyyEnchantingworkbenchfuck
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: BillyyAlchemyworkbenchfuck
      icon: OStim/sexual/missionary_mf
    - sceneId: BillyyGloryholestuckfuck
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: BillyyGloryholefuck
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: BillyyGloryholeblowjob
      icon: OStim/sexual/blowjob_mf
