mods:
    - path: D:\MO2\mods\Anub's additional Ostim starting scenes
    - path: D:\MO2\mods\Anub's animations for Ostim - Human
    - name: Ostim
      path: D:\MO2\mods\OStim Standalone - Advanced Adult Animation Framework
    - name: MLC
      path: D:\MO2\mods\Lovemaking Compendium for OStim Standalone
