icons:
    - sceneId: LeitoStanding2
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: LeitoMissionary3
      icon: OStim/sexual/missionary_mf
    - sceneId: LeitoLotus
      icon: OStim/sexual/carryingsex_mf
    - sceneId: LeitoKissingFemaleStart
      icon: OStim/sensual/kissing_mf
    - sceneId: LeitoDoggy2
      icon: OStim/sexual/doggystyle_mf
    - sceneId: LeitoCunnilingus2
      icon: OStim/sexual/cunnilingus_mf
    - sceneId: LeitoCowgirl2
      icon: OStim/sexual/cowgirl_mf
    - sceneId: LeitoBj3
      icon: OStim/sexual/blowjob_lying_mf
    - sceneId: LeitoBj2
      icon: OStim/sexual/blowjob_mf
    - sceneId: LeitoAnalReCow
      icon: OStim/sexual/reversecowgirl_mf
    - sceneId: LeitoAnalPowerbomb
      icon: OStim/sexual/matingpress_mf
    - sceneId: LeitoAnalMissionary
      icon: OStim/sexual/missionary_mf
    - sceneId: LeitoAnalMissionary2
      icon: OStim/sexual/missionary_mf
    - sceneId: LeitoAnalDoggy2
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: Leito69
      icon: OStim/sexual/sixtynine_mf
