module:
    name: BillyysHuman
    inputPath: D:\animations\billyy\SLAL_Billyy_Animations v7.1
        SE\SLAL_Billyy_Human\meshes\actors\character\animations\Billyy_Human
    slalJsonConfig: D:\animations\billyy\SLAL_Billyy_Animations v7.1
        SE\SLAL_Billyy_Human\SLAnims\json\Billyy_Human.json
    include: []
    exclude: 
        - 5pgb1
        - 5pgb2
        - 5pgb3
        - 4pgang4
        - 4pgang5
        - 4pgang6
        - 4pgang7
        - 4pgb1
        - 4pgb2
        - 4pgb8
        - 4pserv1
        - 4pservgob
        - billyy4pgangbang3
        - 3p69a
        - 3parcspita
        - 3pdoublebj
        - 3pdp1
        - 3pdp2
        - 3pdp3
        - 3pdp4
        - 3pkneelspit
        - 3pmissspit1
        - 3prcgspit
        - 3pspit1
        - 3pspita2
        - 3pspitdoga
        - 3pstandspit1
        - fmast1
        - fmast2
        - fmast3
        - fmast4
        - fmaststaff
        - malemmug
        - mkneelmast1
        - mkneelmast2
        - mlaymast1
        - mstandmast1
        - mstandmast2
        - BillyyBillyy4pgangbang3
        - Billyy3p69a
        - Billyy3parcspita
        - Billyy3pdoublebj
        - Billyy3pdp1
        - Billyy3pdp2
        - Billyy3pdp3
        - Billyy3pdp4
        - Billyy3pkneelspit
        - Billyy3pmissspit1
        - Billyy3prcgspit
        - Billyy3pspit1
        - Billyy3pspita2
        - Billyy3pspitdoga
        - Billyy3pstandspit1
        - Billyy4pgang4
        - Billyy4pgang5
        - Billyy4pgang6
        - Billyy4pgang7
        - Billyy4pgb1
        - Billyy4pgb2
        - Billyy4pgb8
        - Billyy4pserv1
        - Billyy4pservgob
        - Billyy5pgb1
        - Billyy5pgb2
        - Billyy5pgb3
        - BillyyFmast1
        - BillyyFmast2
        - BillyyFmast3
        - BillyyFmast4
        - BillyyFmaststaff
        - BillyyMalemmug
        - BillyyMkneelmast1
        - BillyyMkneelmast2
        - BillyyMlaymast1
        - BillyyMstandmast1
        - BillyyMstandmast2
    nemesisPrefix: bilhum
