icons:
    - sceneId: LeitoFSoloChair
      icon: OStim/sexual/femalemasturbation
    - sceneId: LeitoUnicorn
      icon: OStim/sexual/missionary_mf
    - sceneId: LeitoThroneMissionary
      icon: OStim/sexual/missionary_mf
    - sceneId: LeitoThroneDoggy
      icon: OStim/sexual/doggystyle_mf
    - sceneId: LeitoThroneCunnilingus
      icon: OStim/sexual/cunnilingus_mf
    - sceneId: LeitoThroneCowgirl
      icon: OStim/sexual/chair/cowgirl_mf
    - sceneId: LeitoThroneBj
      icon: OStim/sexual/blowjob_mf
    - sceneId: LeitoThroneAnalReCow
      icon: OStim/sexual/chair/reversecowgirl_mf
    - sceneId: LeitoThroneAnalDoggy
      icon: OStim/sexual/doggystyle_mf
    - sceneId: LeitoBedMissionary
      icon: OStim/sexual/missionary_mf
    - sceneId: LeitoBedFeetMissionary
      icon: OStim/sexual/missionary_mf
    - sceneId: LeitoBedDoggy
      icon: OStim/sexual/doggystyle_mf
    - sceneId: LeitoBedCowgirl
      icon: OStim/sexual/cowgirl_mf
    - sceneId: LeitoBedAnalReCow
      icon: OStim/sexual/reversecowgirl_mf
    - sceneId: LeitoBedAnalDoggy
      icon: OStim/sexual/doggystyle_mf
    - sceneId: LeitoBed69
      icon: OStim/sexual/sixtynine_mf
