icons:
    - sceneId: BillyyL3porgy6
      icon: ""
    - sceneId: BillyyL3porgy5
      icon: ""
    - sceneId: BillyyL3porgy4
      icon: ""
    - sceneId: BillyyL3porgy3
      icon: ""
    - sceneId: BillyyL3porgy2
      icon: ""
    - sceneId: BillyyL3porgy1
      icon: ""
    - sceneId: BillyyLtrib2
      icon: ""
    - sceneId: BillyyLtrib1
      icon: ""
    - sceneId: BillyyLskiss1
      icon: OStim/sensual/kissing_ff
    - sceneId: BillyyLfing5
      icon: OStim/sexual/fingering_f
    - sceneId: BillyyLfing4
      icon: OStim/sexual/fingering_f
    - sceneId: BillyyLfing3
      icon: OStim/sexual/fingering_f
    - sceneId: BillyyLfing2
      icon: OStim/sexual/fingering_f
    - sceneId: BillyyLfing1
      icon: OStim/sexual/fingering_f
    - sceneId: BillyyLesmdil3
      icon: ""
    - sceneId: BillyyLesmdil2
      icon: ""
    - sceneId: BillyyLesmdil1
      icon: ""
    - sceneId: BillyyLesdoubled2
      icon: ""
    - sceneId: BillyyLesdoubled1
      icon: ""
    - sceneId: BillyyLesdilpile
      icon: OStim/sexual/analsex_ff
    - sceneId: BillyyLcunn5
      icon: OStim/sexual/cunnilingus_ff
    - sceneId: BillyyLcunn4
      icon: OStim/sexual/cunnilingus_behind_ff
    - sceneId: BillyyLcunn3
      icon: OStim/sexual/cunnilingus_behind_ff
    - sceneId: BillyyLcunn2
      icon: OStim/sexual/cunnilingus_ff
    - sceneId: BillyyLcunn1
      icon: ""
    - sceneId: BillyyL69side
      icon: ""
    - sceneId: BillyyL69
      icon: ""
