icons:
    - sceneId: BillyySthighf
      icon: OStim/sexual/thighjob_mf
    - sceneId: BillyyStandface
      icon: ""
    - sceneId: BillyyStandbj
      icon: OStim/sexual/blowjob_mf
    - sceneId: BillyyStanda
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: BillyyStand
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: BillyySquatbj
      icon: OStim/sexual/blowjob_mf
    - sceneId: BillyySquat
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: BillyySpooningfacing
      icon: OStim/sexual/sideways_mf
    - sceneId: BillyySpankstand
      icon: OStim/sexual/spank_mf
    - sceneId: BillyySpankdog
      icon: OStim/sexual/spank_mf
    - sceneId: BillyySkiss1
      icon: OStim/sensual/kissing_mf
    - sceneId: BillyySitbj
      icon: OStim/sexual/blowjob_mf
    - sceneId: BillyySide
      icon: OStim/sexual/sideways_mf
    - sceneId: BillyyRjdog
      icon: OStim/sexual/anilingus_mf
    - sceneId: BillyyRevlotus2
      icon: ""
    - sceneId: BillyyRevlotus
      icon: ""
    - sceneId: BillyyRcg2
      icon: OStim/sexual/reversecowgirl_mf
    - sceneId: BillyyNellay
      icon: ""
    - sceneId: BillyyMissa
      icon: OStim/sexual/missionary_mf
    - sceneId: BillyyMatingp
      icon: OStim/sexual/matingpress_mm
    - sceneId: BillyyMalesitbj
      icon: OStim/sexual/blowjob_mf
    - sceneId: BillyyLotussit
      icon: ""
    - sceneId: BillyyLegup
      icon: ""
    - sceneId: BillyyLaytitf
      icon: OStim/sexual/boobjob_mf
    - sceneId: BillyyLayprone
      icon: ""
    - sceneId: BillyyLayingblowjob
      icon: OStim/sexual/blowjob_lying_mf
    - sceneId: BillyyLaycunn
      icon: OStim/sexual/cunnilingus_mf
    - sceneId: BillyyLaybjdog
      icon: OStim/sexual/blowjob_lying_mf
    - sceneId: BillyyLaybff
      icon: OStim/sexual/facefuck_mf
    - sceneId: BillyyLayba
      icon: ""
    - sceneId: BillyyLayanal
      icon: ""
    - sceneId: BillyyLay692
      icon: OStim/sexual/sixtynine_mf
    - sceneId: BillyyKneff
      icon: OStim/sexual/facefuck_mf
    - sceneId: BillyyKneelbj3
      icon: OStim/sexual/blowjob_mf
    - sceneId: BillyyKneelbj2
      icon: OStim/sexual/blowjob_mf
    - sceneId: BillyyHold
      icon: OStim/sexual/carryingsex_mf
    - sceneId: BillyyHj3lay
      icon: OStim/sexual/handjob_mf
    - sceneId: BillyyHj2
      icon: OStim/sexual/handjob_mf
    - sceneId: BillyyHj1
      icon: OStim/sexual/handjob_mf
    - sceneId: BillyyFj
      icon: OStim/sexual/footjob_mf
    - sceneId: BillyyFacesitcunn
      icon: ""
    - sceneId: BillyyFinger2
      icon: OStim/sexual/vaginalfingering_mf
    - sceneId: BillyyFinger1
      icon: OStim/sexual/vaginalfingering_mf
    - sceneId: BillyyFhjmiss
      icon: OStim/sexual/handjob_mf
    - sceneId: BillyyFhjstand
      icon: OStim/sexual/handjob_mf
    - sceneId: BillyyDoggyarm
      icon: OStim/sexual/doggystyle_mf
    - sceneId: BillyyDoggy1
      icon: OStim/sexual/doggystyle_mf
    - sceneId: BillyyDogbj
      icon: OStim/sexual/blowjob_mf
    - sceneId: BillyyCthighj
      icon: OStim/sexual/thighjob_mf
    - sceneId: BillyyCrabmiss
      icon: ""
    - sceneId: BillyyCowgirl1
      icon: OStim/sexual/cowgirl_mf
    - sceneId: BillyyCglay
      icon: OStim/sexual/cowgirl_mf
    - sceneId: BillyyCggrind
      icon: OStim/sexual/cowgirl_mf
    - sceneId: BillyyCganal
      icon: OStim/sexual/cowgirl_mf
    - sceneId: BillyyCg2squatt
      icon: OStim/sexual/cowgirl_mf
    - sceneId: BillyyBehmeme
      icon: OStim/sexual/doggystyle_mf
