icons:
    - sceneId: BillyyMstandmast2
      icon: OStim/sexual/malemasturbation
    - sceneId: BillyyMstandmast1
      icon: OStim/sexual/malemasturbation
    - sceneId: BillyyMlaymast1
      icon: OStim/sexual/malemasturbation
    - sceneId: BillyyMkneelmast2
      icon: OStim/sexual/malemasturbation
    - sceneId: BillyyMkneelmast1
      icon: OStim/sexual/malemasturbation
    - sceneId: BillyyMalemmug
      icon: OStim/sexual/malemasturbation
