icons:
    ofdaut_f:
        - aanaldoggy
        - adultdoggy2
        - anubdoggystyle
        - jacko
        - chairdoggy
        - atable
        - awall4
        - ffmmistress
    osc_mufold_mf:
        - adultmissionary
        - adultmatingpress
        - adultsleep
        - am2
        - bm
        - d6b
        - deltafeet
        - impreg
        - legupfuck
        - misionary
        - ainvtable
    osx_layside_f:
        - adultls
        - adultspooning
    otiptoedn_f:
        - adultfootjob
    okalbdn_f:
        - adultrcg2
        - lustcowgirl
        - mmocg
        - nelson
        - rcowgirl
        - adultbench
        - fmm3some
        - gangbang
    ohjugxs2_9_f:
        - adulttease2
        - foreplay
        - ffmsleep
    osn_st9ho_mf:
        - asq
        - standingnew
        - vampfemale
    osn_st6ho_mf:
        - ast
        - sinner
        - vamp1
    osc_handledbj_f:
        - a69
        - d6s
        - squatingbj
    osx_tumli_f:
        - apronebone
    osn_lflotus_mf:
        - hold
        - ffmm
