module:
    name: AnubsHuman
    inputPath: D:\animations\anubs\1346682956_AnubSLAL01.2023LE\00 Data\SLAL
        H\Meshes\actors\character\animations\Anubs Human
    slalJsonConfig: D:\animations\anubs\1346682956_AnubSLAL01.2023LE\00 Data\SLAL
        H\SLAnims\json\HUMAN NEW.json
    include:
        - ffmm
        - ffmmistress
        - ffmsleep
        - adultbench
        - chairdoggy
        - gangbang
        - fmm3some
        - a69
        - aanaldoggy
        - adultdoggy2
        - adultrcg2
        - adultfootjob
        - adultls
        - adultmatingpress
        - adultmissionary
        - adultsleep
        - adultspooning
        - adulttease2
        - am2
        - apronebone
        - anubdoggystyle
        - asq
        - ast
        - bm
        - d6b
        - d6s
        - deltafeet
        - foreplay
        - hold
        - impreg
        - jacko
        - legupfuck
        - lustcowgirl
        - misionary
        - mmocg
        - nelson
        - rcowgirl
        - sinner
        - squatingbj
        - standingnew
        - vamp1
        - vampfemale
        - ainvtable
        - atable
        - awall4
    exclude:
        - amazon
        - anubagra
        - bound
        - humandoggy
        - missionaryr
        - rape
        - rejection
        - fcowgirl
        - mmfrape
        - choke
        - sdefeat
        - magick
        - mbf
        - ff
        - abg
        - hogtie3some
        - ahb
        - knife
        - x
        - vs
        - chained
        - chaingallow
        - chainedcelling
        - pole
        - paralysis
        - unc2
        - unc
        - hypno
        - mindcontrol
        - cancun
        - chaurustest
        - ashotacowgirl
        - swordcg
        - dildo
        - chest
        - barrelmast
        - caged
        - adultstool
        - adultbath
        - aside
        - drunk
        - tw
        - asofa
        - adultbartable
        - anubcounter
        - training
        - abed2
        - abedsleep
        - adultbed
        - bedp
        - adultrbed2
        - ffmbed
        - ffmbed2
        - awallc
        - wallback
        - wallfront
        - wallside
        - boundtable
        - achaircg
        - chairfemdom
