specialSwapRules:
    gangbang:
        applyToAllStages: false
        stages:
            - - 1
              - 2
              - 0
              - 3
            - null
            - null
            - null
    ffmm:
        applyToAllStages: true
        stages:
            - - 2
              - 1
              - 3
              - 0
            - null
            - null
            - null
            - null
            - null
