icons:
    - sceneId: AnubsLesbiandomination
      icon: OStim/sexual/cunnilingus_ff
    - sceneId: AnubsLesbian
      icon: OStim/sexual/cunnilingus_ff
    - sceneId: AnubsLesbianFf
      icon: OStim/sexual/cunnilingus_ff
    - sceneId: AnubsFffmistress
      icon: ""
