icons:
    - sceneId: NibblesWorkbench
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: NibblesTablestandingfront
      icon: OStim/sexual/table/missionary_mf
    - sceneId: NibblesTablestandingbehind
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: NibblesTablefuck
      icon: OStim/sexual/table/missionary_mf
    - sceneId: NibblesSpanking
      icon: OStim/sexual/spank_left_mf
    - sceneId: NibblesSpankingchair
      icon: OStim/sexual/spank_left_mf
    - sceneId: NibblesTentacledoggy
      icon: ""
    - sceneId: NibblesMimic
      icon: ""
    - sceneId: NibblesLesbianhaycun
      icon: OStim/sexual/cunnilingus_ff
    - sceneId: NibblesChairdildo
      icon: OStim/sexual/strapon_insert_vert
    - sceneId: NibblesDrunkmasturbation
      icon: OStim/sexual/femalemasturbation
