module:
    name: NibblesSpawnedFurniture
    inputPath: D:\animations\nibbles\SLAL NibblesAnims
        5.81\Objects\Meshes\actors\character\animations\NibblesAnims_Object
    slalJsonConfig: D:\animations\nibbles\SLAL NibblesAnims
        5.81\Objects\SLAnims\json\NibblesAnims_OBJECTS.json
    include: []
    exclude:
        - NibblesDildo
        - NibblesBondagepost
        - NibblesBondageposttoy
        - NibblesBondageposttoyfemdom
        - NibblesBondagepostfemdom
        - NibblesBondagepostblowjob
        - NibblesPillory
    nemesisPrefix: nibsfu
