module:
    name: AnubsBigGuy
    inputPath: D:\animations\anubs\1346682956_AnubSLAL01.2023LE\00 Data\SLAL
        H\Meshes\actors\character\animations\Anubs Human
    slalJsonConfig: D:\animations\anubs\1346682956_AnubSLAL01.2023LE\00 Data\SLAL
        H\SLAnims\json\HUMAN NEW.json
    include:
        - mmfbigguys
        - bggentle
        - bgnelson
        - bigguydoggy
        - bigguysitting
        - bgwall
    exclude: []
