furnitureMap:
    bed:
        - AnubsABed2
        - AnubsAdultBed
        - AnubsFfmBed2
    bench: []
    chair: []
    cookingpot: []
    shelf: []
    table:
        - AnubsAInvTable
        - AnubsATable
        - AnubsAnubCounter
    wall:
        - AnubsAWall4
        - AnubsAWallc
        - AnubsLesbianWc
        - AnubsWallback
        - AnubsWallside
        - AnubsWallfront
