furnitureMap:
    bed:
        - abed2
        - adultbed
        - ffmbed2
    bench: []
    chair: []
    cookingpot: []
    shelf: []
    table:
        - ainvtable
        - atable
        - anubcounter
    wall:
        - awall4
        - awallc
        - lesbianwc
        - wallback
        - wallside
