furnitureMap:
    - animation: AnubsABed2
      furniture: bed
    - animation: AnubsAdultBed
      furniture: bed
    - animation: AnubsFfmBed2
      furniture: bed
    - animation: AnubsAInvTable
      furniture: table
    - animation: AnubsATable
      furniture: table
    - animation: AnubsAnubCounter
      furniture: table
    - animation: AnubsAWall4
      furniture: wall
    - animation: AnubsAWallc
      furniture: wall
    - animation: AnubsLesbianWc
      furniture: wall
    - animation: AnubsWallback
      furniture: wall
    - animation: AnubsWallside
      furniture: wall
    - animation: AnubsWallfront
      furniture: wall
