icons:
    - sceneId: AnubsAInvTable
      icon: OStim/sexual/table/missionary_legsup_mf
    - sceneId: AnubsAnubCounter
      icon: OStim/sexual/table/missionary_mf
    - sceneId: AnubsATable
      icon: OStim/sexual/table/missionary_mf
    - sceneId: AnubsABed2
      icon: OStim/sexual/reversecowgirl_mf
    - sceneId: AnubsAdultBed
      icon: OStim/sexual/doggystyle_mf
    - sceneId: AnubsAWall4
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: AnubsAWallc
      icon: ""
    - sceneId: AnubsWallback
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: AnubsWallfront
      icon: OStim/sexual/carryingsex_mf
    - sceneId: AnubsWallside
      icon: ""
    - sceneId: AnubsFfmBed2
      icon: ""
    - sceneId: AnubsLesbianWc
      icon: ""
