module:
    name: BillyysSoloF
    inputPath: D:\animations\billyy\SLAL_Billyy_Animations v7.1
        SE\SLAL_Billyy_Human\meshes\actors\character\animations\Billyy_Human
    slalJsonConfig: D:\animations\billyy\SLAL_Billyy_Animations v7.1
        SE\SLAL_Billyy_Human\SLAnims\json\Billyy_Human.json
    include:
        - BillyyFmast1
        - BillyyFmast2
        - BillyyFmast3
        - BillyyFmast4
        - BillyyFmaststaff
    exclude: []
    nemesisPrefix: bilsof
