icons:
    ofdaut_f:
        - ffmreversal
    okalbdn_f:
        - anubdomcow
        - anubfemdom
        - aamazon
        - afc2
        - thronefemdom
        - ffmfemdom3
    ohjugxs2_9_f:
        - femfoot
    osc_handledbj_f:
        - facesit
