icons:
    - sceneId: AnubsAfc2
      icon: OStim/sexual/cowgirl_mf
    - sceneId: AnubsAmazon
      icon: OStim/sexual/cowgirl_mf
    - sceneId: AnubsAnubdomcow
      icon: OStim/sexual/cowgirl_mf
    - sceneId: AnubsFemfoot
      icon: OStim/sexual/footjob_mf
    - sceneId: AnubsHypno
      icon: OStim/sexual/bendover_standing_mf
    - sceneId: AnubsKnife
      icon: OStim/sexual/cowgirl_mf
    - sceneId: AnubsSwordCg
      icon: OStim/sexual/reversecowgirl_mf
    - sceneId: AnubsAnubfemdom
      icon: ""
    - sceneId: AnubsAAmazon
      icon: ""
    - sceneId: AnubsFacesit
      icon: OStim/sexual/facesitting_mf
    - sceneId: AnubsFfmfemdom2
      icon: ""
    - sceneId: AnubsFfmfemdom
      icon: ""
    - sceneId: AnubsFfmReversal
      icon: ""
    - sceneId: AnubsHge
      icon: ""
    - sceneId: AnubsMbf
      icon: OStim/action/magic_f
