nemesisTransitionToolExe: D:\Tools\AnimlistTransitionTool\src\bin\Release\net6.0-windows8.0\Animlist
    Transition Tool.exe
hkannoExe: D:\Tools\hkanno64-001\hkanno64.exe
ostimAlignmentJsonPath: C:\Users\sokol\Documents\My Games\Skyrim Special Edition\OStim\alignment.json
