main:
    addonHubPath: D:\MO2\mods\OpenSex Addon Hub
    outputPath: D:\MO2\mods\Custom patches OpenSex
    prependNewOptions: true
modsToConnect:
    - name: asd
      path: D:\MO2\mods\Custom animations
      isGenerated: true
addonHubs:
    bench: OpS_addon\BenCh\Ap\BenchAddonHub.xml
    chair: OpS_addon\ChaIr\Ap\ChairAddonHub.xml
    wall: OpS_addon\WaLl\Ap\WallAddonHub.xml
    main: OpS_addon\StaSta\Ap\AddonHub.xml
    table: OpS_addon\TabLe\Ap\TableAddonHub.xml
